// <auto-generated />
using AccountMicroservice.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace AccountMicroservice.Migrations
{
    [DbContext(typeof(AccountMicroserviceDbContext))]
    [Migration("20210923155918_AddAccountToDb")]
    partial class AddAccountToDb
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.10")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("AccountMicroservice.Model.Account", b =>
                {
                    b.Property<int>("MyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<double>("Balance")
                        .HasColumnType("float");

                    b.Property<int>("Cur_AccountId")
                        .HasColumnType("int");

                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<double>("MinBalance")
                        .HasColumnType("float");

                    b.Property<int>("Sav_AccountId")
                        .HasColumnType("int");

                    b.Property<string>("accountType")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MyId");

                    b.ToTable("Accounts");
                });
#pragma warning restore 612, 618
        }
    }
}
